spring:
  datasource:
    url: jdbc:mysql://139.224.213.105:3306/mybatis_plus?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: piyihao
    driver: com.mysql.cj.jdbc.Driver

#mybatis-plus:
#  global-config:
#    db-config:
#      logic-not-delete-value: 1
#      logic-delete-value: -1

